server:
  port: 9002
spring:
  application:
    name: myshop-web
  datasource:
    url: jdbc:mysql://10.211.55.4:3306/springcloud?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
    register-with-eureka: true # 作为客户端，注册到Eureka
    fetch-registry: true # 作为客户端，从Eureka获取注册信息
  instance:
    prefer-ip-address: true # 优先使用该服务的IP地址注册到Eureka，在生产环境建议改为true
#  myshop-user:
#    ribbon:
#      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 设置Ribbon的负载均衡策略为随机
logging:
  level:
    com.netflix.loadbalancer: DEBUG
feign:
  hystrix:
    enabled: true